- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    gcp_region: us-east1
    gcp_zone: us-east1-b
    gcp_project: true-entropy-221110 
    gcp_cred_kind: serviceaccount
    gcp_cred_file: ../credentials.json
    source_image: projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20181030

  roles:
    #create network
    - role: gcp-network

    #create gitaly
    - role: gcp-instance
      vars:
        gcp_machine_type: n1-standard-1
        instances:
          - { index: 1, tag: gitaly }
          - { index: 2, tag: gitaly }
        disk_size: 30
        disk_type: pd-standard
        type: gitaly
    #create app
    - role: gcp-instance
      vars:
        gcp_machine_type: n1-standard-1
        instances:
          - { index: 1, tag: app}
        disk_size: 30
        disk_type: pd-standard
        type: gitlab-app

- hosts: all
  become: yes
  tasks:
    - name: Wait for instances to respond
      wait_for:
        host: "{{ item }}"
        port: 22
      loop: "{{ groups['all'] }}"
    - name: Wait for updates to finish
      shell: while pgrep apt; do sleep 1; done;

- hosts: localhost
  tasks:
    - name: Copy gitlab.yml
      shell: |
        cp gitlab.yml.example gitlab.yml
    - name: Register gitaly default address
      shell: |
        sed -i.bak '613i\
        \ \ \ \ \ \ default:
        ' gitlab.yml
        sed -i.bak '614i\
        \ \ \ \ \ \ \ \ path: /home/git/repositories
        ' gitlab.yml
        sed -i.bak '615i\
        \ \ \ \ \ \ \ \ gitaly_address: tcp://{{ hostvars[item].ansible_default_ipv4.address }}:8075
        ' gitlab.yml
      loop: "{{groups[\"gitaly\"]}}"
      loop_control:
        index_var: idx
      when: idx == 0
    - name: Register other gitaly adresses
      shell: |
        sed -i.bak '616i\
        \ \ \ \ \ \ respository{{idx}}:
        ' gitlab.yml
        sed -i.bak '617i\
        \ \ \ \ \ \ \ \ path: /home/git/repositories{{idx}}
        ' gitlab.yml
        sed -i.bak '618i\
        \ \ \ \ \ \ \ \ gitaly_address: tcp://{{ hostvars[item].ansible_default_ipv4.address }}:8075
        ' gitlab.yml
      loop: "{{groups[\"gitaly\"]}}"
      loop_control:
        index_var: idx
      when: idx != 0
- hosts: app
  become: yes
  tasks:
    - name: Copy gitlab.yml to gitlab-app instances
      copy:
        src: ./gitlab.yml
        dest: ~/gitlab.yml
- hosts: gitaly
  become: yes
  roles:
    - { role: gitaly }

- hosts: app
  become: yes
  roles:
    - { role: app }

