- name: Install Mysql
  apt: pkg=mysql-server state=latest

- name: Set MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_pass | quote}}' vtype='password'

- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_pass | quote}}' vtype='password'

- name: Install pip
  apt:
    name: python-pip
    update_cache: yes
    state: present

- pip:
    name: PyMySQL

- name: Start the MySQL service
  sudo: yes
  service:
    name: mysql
    state: started
    enabled: true
- name: Create `/root/.my.cnf`  with root password credentials
  template:
    src:  my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600



- name: Find temporary password
  shell: "echo `grep 'temporary.*root@localhost' /var/log/mysqld.log | sed
's/.*root@localhost: //'`"
  register: mysql_root_password_temp
  tags: register

- name: Set new password from temporary password
  shell: 'mysql -e "SET PASSWORD = PASSWORD(''{{ mysql_root_pass }}'');"
--connect-expired-password -u root -p"{{ mysql_root_password_temp.stdout }}"'

- name: Restart the MySQL service
  become: yes
  service:
    name: mysql
    state: restarted
    enabled: true

#- name: Create a new database with name 'storagesystem'
#  sudo: yes
#  mysql_db:
#    name: storagesystem
#    state: present
#    login_user: root
#    login_password: root

- copy:
    src: storage-system-schema.sql
    dest: /tmp/storage-system-schema.sql

- name: Import schema.sql
  mysql_db:
    state: import
    name: all
    target: /tmp/storage-system-schema.sql
