- name: Copy gitlab.yml to gitlab-app instances
  copy:
    src: ./gitlab.yml
    dest: /home/sdb/gitlab.yml

- name: Copy database.yml to gitlab-app instances
  copy:
    src: ./database.yml
    dest: /home/sdb/database.yml

- name : Copy resque.yml to gitlab-app instances
  copy:
    src: ./resque.yml
    dest: /home/sdb/resque.yml

- name: Copy gitlab-shell secret to gitlab-app instances
  copy:
    src: ./.gitlab_shell_secret
    dest: /home/sdb/.gitlab_shell_secret

- name: Copy unicorn.rb to gitlab-app instances
  copy:
    src: ./unicorn.rb
    dest: /home/sdb/unicorn.rb