- name: Add Elastic repo
  block:
    - apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
    - lineinfile:
        path: /etc/apt/sources.list.d/elastic-6.x.list
        line: "deb https://artifacts.elastic.co/packages/6.x/apt stable main"
        create: yes

- name: Install Java
  apt:
    name: openjdk-8-jre
    state: latest

- name: Install ElasticSearch and Kibana
  apt:
    name: ['elasticsearch', 'kibana']
    state: latest

#- name: Configure Logstash
#  copy:
#    src: logstash.yml
#    dest: /etc/logstash/logstash.yml

- name: Configure ElasticSearch
  copy:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml

- name: Install ingest-geoip plugin
  become: yes
  shell: "/usr/share/elasticsearch/bin/elasticsearch-plugin install ingest-geoip --batch"

- name: Configure Kibana
  copy:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml

- name: Start ElasticSearch
  service:
    name: elasticsearch
    enabled: yes
    state: started

- name: Start Kibana
  service:
    name: kibana
    enabled: yes
    state: started