- name: Install Redis Server
  apt:
    name: [redis-server]
    state: latest

- name: Configuring Redis Server and Restart
  block:
    #redis conf
    - template:
        src: redis.conf.j2
        dest: /etc/redis/redis.conf
    #create user git
    - user:
        name: git
        comment: 'Gitlab'
        groups: redis
        append: yes
    #create directory redis
    - file:
        path: /var/run/redis
        state: directory
        owner: redis
        group: redis
        mode: 0755
    - shell: |
        if [ -d /etc/tmpfiles.d ]; then
          echo 'd  /var/run/redis  0755  redis  redis  10d  -' | sudo tee -a /etc/tmpfiles.d/redis.conf
        fi
    #restart service
    - service:
        name: redis-server
        state: restarted
        enabled: yes

- name: Configuring Redis Sentinel
  block:
    - template:
        src: redissentinel.conf.j2
        dest: /etc/redis/sentinel.conf

- name: Running Redis Sentinel
  shell: |
    sudo chmod +rw /etc/redis/sentinel.conf
    sudo redis-server /etc/redis/sentinel.conf --sentinel &
